---
- name: Enable HHVM repo key
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present
- name: Enable HHVM repo
  apt_repository: repo="deb http://dl.hhvm.com/ubuntu trusty main" state=present
- name: Install HHVM
  apt: name=hhvm state=present
