---
- name: Enable Percona repo key
  command: apt-key adv --keyserver keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
- name: Enable Percona repo
  apt_repository: repo="deb http://repo.percona.com/apt trusty main" state=present
- name: Install Percona server
  apt: name=percona-server-server-5.6 state=present
- name: Install Percona client
  apt: name=percona-server-client-5.6 state=present
- name: Ensure Percona is running
  service: name=percona state=started
